//
// main.go
// Rebuilds the embedded classification lists from their upstream sources.
//
// Created: 2026-09-03
// Copyright (c) 2026 Cloudmanic Labs, LLC. All rights reserved.
//

// Command gen-lists writes internal/ingest/lists/datacenters.txt from the
// ranges each cloud provider publishes about itself. It is a build-time tool,
// never embedded in the product, and its output is committed so that `go build`
// works from a clean checkout with no network.
//
// Run it with `make lists`.
package main

import (
	"context"
	"flag"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/Feasible-Analytics/app.feasible.lol/internal/ingest/lists"
)

// main fetches every source, merges the result and writes the file.
func main() {
	out := flag.String("out", filepath.Join("internal", "ingest", "lists", "datacenters.txt"),
		"file to write the merged ranges into")
	flag.Parse()

	if err := run(*out); err != nil {
		fmt.Fprintln(os.Stderr, "gen-lists:", err)
		os.Exit(1)
	}
}

// run does the work. A source that fails is reported and skipped rather than
// fatal, because one provider having a bad morning must not leave the tree with
// no list at all — but a run that loses a source says so loudly, and the
// coverage floor below refuses to write a file that lost most of them.
func run(out string) error {
	client := &http.Client{Timeout: lists.FetchTimeout}
	ctx := context.Background()

	sources := lists.DatacenterSources()

	if azure, err := lists.AzureSource(ctx, client, time.Now()); err != nil {
		fmt.Fprintln(os.Stderr, "  ! Azure:", err)
	} else {
		sources = append(sources, azure)
	}

	var (
		all    []string
		failed []string
	)

	for _, source := range sources {
		cidrs, err := lists.Fetch(ctx, client, source)
		if err != nil {
			fmt.Fprintln(os.Stderr, "  !", err)
			failed = append(failed, source.Name)

			continue
		}

		fmt.Printf("  %-16s %6d prefixes\n", source.Name, len(cidrs))
		all = append(all, cidrs...)
	}

	// Half the sources missing is a network problem at this end, not a list.
	// Writing it would quietly halve the coverage of every build that follows.
	if len(failed)*2 >= len(sources) {
		return fmt.Errorf("%d of %d sources failed: %s",
			len(failed), len(sources), strings.Join(failed, ", "))
	}

	merged := lists.Merge(all)
	sort.Strings(merged)

	fmt.Printf("\n  %d prefixes merged to %d ranges\n", len(all), len(merged))

	return write(out, merged, sources, failed)
}

// write renders the file. The header names the sources rather than the date:
// a date changes every run and turns a no-op regeneration into a diff, while
// the source list is the thing a reader actually needs to judge the file by.
func write(out string, ranges []string, sources []lists.Source, failed []string) error {
	names := make([]string, 0, len(sources))
	for _, source := range sources {
		names = append(names, source.Name)
	}

	var body strings.Builder

	body.WriteString("# datacenters.txt\n")
	body.WriteString("# Hosting and cloud-compute address ranges. Generated by cmd/gen-lists;\n")
	body.WriteString("# run `make lists` to rebuild. Do not edit by hand.\n")
	body.WriteString("#\n")
	body.WriteString("# Every range here comes from the provider describing its own network.\n")
	body.WriteString("# Cloudflare, Fastly and Akamai are deliberately absent: their address\n")
	body.WriteString("# space carries WARP and iCloud Private Relay, which are real people.\n")
	body.WriteString("#\n")
	body.WriteString("# Sources: " + strings.Join(names, ", ") + "\n")

	if len(failed) > 0 {
		body.WriteString("# Missing at generation time: " + strings.Join(failed, ", ") + "\n")
	}

	body.WriteString("\n")

	for _, entry := range ranges {
		body.WriteString(entry)
		body.WriteString("\n")
	}

	if err := os.WriteFile(out, []byte(body.String()), 0o644); err != nil {
		return err
	}

	fmt.Printf("  wrote %s\n", out)

	return nil
}
